version: '3'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "4080:4080/tcp"
      - "4081:4081/tcp"
    hostname: mitmproxy
    container_name: mitmproxy
    command: mitmweb --showhost --listen-port 4080 --web-host 0.0.0.0 --web-port 4081
